### ISSUE TITLE
pip install fails on acessing README.md

### ISSUE THREAD

**Issue by cben** [LABHR/ye_olde_octohat#1]
FWIW, the meta-package doesn't install for me (`pip3 install octohatrack` does work, this is only about the redirect, in case you still want to maintain it).  I'm on Fedora 27 linux.
```
~ $ pip3 --version
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)
~ $ pip --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
~ $ pip3 install octohat --user
Collecting octohat
  Using cached octohat-0.1.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9e4_7262/octohat/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/lib64/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-9e4_7262/octohat/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9e4_7262/octohat/
```
Same for `pip install octohat --user`, sudo instead of --user doesn't help either.
Some more details:
```
~ $ pip3 install octohat --user -vvv --no-clean
Collecting octohat
  1 location(s) to search for versions of octohat:
  * https://pypi.python.org/simple/octohat/
  Getting page https://pypi.python.org/simple/octohat/
  Looking up "https://pypi.python.org/simple/octohat/" in the cache
  Current age based on date: 785
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The cached response is "stale" with no etag, purging
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/octohat/ HTTP/1.1" 200 578
  Updating cache with response from "https://pypi.python.org/simple/octohat/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/octohat/
    Found link https://pypi.python.org/packages/a1/8e/4c7272253a9d53e4727cdf3c5d0a2a3afa93622fe3ba4076384bf446f4fb/octohat-0.0.2.tar.gz#md5=4f964871a08f0c4360b48193ab44310b (from https://pypi.python.org/simple/octohat/), version: 0.0.2
    Found link https://pypi.python.org/packages/b5/c1/3b4c89fff3a8ae1cf70171d41752dd8a0a0105bb8ae7fed9936e6d3b4c08/octohat-0.0.1.tar.gz#md5=f6abc07d3a919f85d7802c181eb9efe1 (from https://pypi.python.org/simple/octohat/), version: 0.0.1
    Found link https://pypi.python.org/packages/d2/c4/76fc0ce922a87a874b37b692f99af5e53b989e1aa4eb2affca3dba47febf/octohat-0.1.3.tar.gz#md5=c689e726ed0d3f6a5e342f23d713c682 (from https://pypi.python.org/simple/octohat/), version: 0.1.3
    Found link https://pypi.python.org/packages/d9/5b/dffbd785e16134bf8a8775e084a39c79b7f551d877fdfc3f5f091070bbd0/octohat-0.1.1.tar.gz#md5=619b7f79c775233b6684e64131db735d (from https://pypi.python.org/simple/octohat/), version: 0.1.1
    Found link https://pypi.python.org/packages/dd/a6/a4a09de08713ce2ba68f2bd08dd4c45ac5294330673ecb203d2dce746e84/octohat-0.1.9.tar.gz#md5=13ed44eed87ac39e26a3efe317a85d8b (from https://pypi.python.org/simple/octohat/), version: 0.1.9
    Found link https://pypi.python.org/packages/fd/46/7287c2346dc4f4bd0b7205d5fe8c0dc6ca2e9904bfe2182a57ececff7e13/octohat-0.1.0.tar.gz#md5=cbd5c981ea43cf4021552748f8f9edd6 (from https://pypi.python.org/simple/octohat/), version: 0.1.0
  Using version 0.1.9 (newest of versions: 0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.1.3, 0.1.9)
  Looking up "https://pypi.python.org/packages/dd/a6/a4a09de08713ce2ba68f2bd08dd4c45ac5294330673ecb203d2dce746e84/octohat-0.1.9.tar.gz" in the cache
  Current age based on date: 785
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 785
  Using cached octohat-0.1.9.tar.gz
  Downloading from URL https://pypi.python.org/packages/dd/a6/a4a09de08713ce2ba68f2bd08dd4c45ac5294330673ecb203d2dce746e84/octohat-0.1.9.tar.gz#md5=13ed44eed87ac39e26a3efe317a85d8b (from https://pypi.python.org/simple/octohat/)
  Running setup.py (path:/tmp/pip-build-r61zsrt0/octohat/setup.py) egg_info for package octohat
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r61zsrt0/octohat/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/lib64/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-r61zsrt0/octohat/README.md'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-r61zsrt0/octohat/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 346, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-r61zsrt0/octohat/
~ $ find /tmp/pip-build-r61zsrt0/ -ls
  9694496      0 drwx------   3  bpaskinc bpaskinc       60 Feb 21 11:37 /tmp/pip-build-r61zsrt0/
  9694514      0 drwxr-xr-x   4  bpaskinc bpaskinc      160 Feb 21 11:37 /tmp/pip-build-r61zsrt0/octohat
  9694525      0 drwxr-xr-x   2  bpaskinc bpaskinc       40 Feb 21 11:37 /tmp/pip-build-r61zsrt0/octohat/pip-egg-info
  9694524      4 -rw-r--r--   1  bpaskinc bpaskinc      185 Feb 21 11:37 /tmp/pip-build-r61zsrt0/octohat/pip-delete-this-directory.txt
  9694523      4 -rw-r--r--   1  bpaskinc bpaskinc      686 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/setup.py
  9694522      4 -rw-r--r--   1  bpaskinc bpaskinc       59 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/setup.cfg
  9694521      4 -rw-r--r--   1  bpaskinc bpaskinc      686 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/PKG-INFO
  9694515      0 drwxr-xr-x   2  bpaskinc bpaskinc      140 Feb 21 11:37 /tmp/pip-build-r61zsrt0/octohat/octohat.egg-info
  9694520      4 -rw-r--r--   1  bpaskinc bpaskinc        1 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/octohat.egg-info/top_level.txt
  9694519      4 -rw-r--r--   1  bpaskinc bpaskinc      162 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/octohat.egg-info/SOURCES.txt
  9694518      4 -rw-r--r--   1  bpaskinc bpaskinc       12 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/octohat.egg-info/requires.txt
  9694517      4 -rw-r--r--   1  bpaskinc bpaskinc      686 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/octohat.egg-info/PKG-INFO
  9694516      4 -rw-r--r--   1  bpaskinc bpaskinc        1 Nov 21  2015 /tmp/pip-build-r61zsrt0/octohat/octohat.egg-info/dependency_links.txt
```

**Comment by cben** [comment]
OK looks like README.md is really missing from [octohat-0.1.9.tar.gz](https://pypi.python.org/packages/dd/a6/a4a09de08713ce2ba68f2bd08dd4c45ac5294330673ecb203d2dce746e84/octohat-0.1.9.tar.gz#md5=13ed44eed87ac39e26a3efe317a85d8b) on PyPI, and the way setup.py is written won't work without it.

**Comment by cben** [comment]
Apropos bit rotting redirects, http://github.com/glasnt/octocat no longer redirects, gives 404.  Weird, redirects on rename are a really nice Github feature, no idea what could cause it to stop working ¯\\\_(ツ)\_/¯.
